Failing junit-reporter removed from resilience test.

diff --git a/.github/workflows/resilence.yaml b/.github/workflows/resilence.yaml
--- a/.github/workflows/resilence.yaml
+++ b/.github/workflows/resilence.yaml
@@ -40,11 +40,11 @@ jobs:
       - name: Reliability tests
         run: ./gradlew clean -Penvironment=integration :envoy-control-tests:reliabilityTest -DRELIABILITY_FAILURE_DURATION_SECONDS=20
 
-      - name: Junit report
-        uses: allegro-actions/junit-reporter@v1
-        if: ${{ success() || failure() }}
-        with:
-          path: '**/test-results/*/*.xml'
+#      - name: Junit report
+#        uses: allegro-actions/junit-reporter@v1
+#        if: ${{ success() || failure() }}
+#        with:
+#          path: '**/test-results/*/*.xml'
 
       - name: Cleanup Gradle Cache
         run: |
